module.exports = {
  name: 'vant-icon',
  basic: [
    'success',
    'plus',
    'cross',
    'arrow',
    'arrow-left',
    'arrow-up',
    'arrow-down'
  ],
  outline: [
    // has corresponding filled icon
    'user-o',
    'close',
    'gem',
    'cancel',
    'location-o',
    'wap-home-o',
    'sign',
    'scan',
    'clock-o',
    'smile-o',
    'add',
    // 'circle',
    'replay',
    // 'square',
    // 'square-checked',
    'closed-eye',
    'search',
    'play-circle-o',
    'edit',
    'feedback',
    'warning-o',
    'delete',
    'calendar',
    'comment',
    'copy',
    'toolbox',
    'testsheet',
    'record',
    'recharge',
    'guidance',
    'menu',
    'surgery-inquiry',
    'vaccination',
    'hospital-introduce',
    'doctor-introduce',
    'patient-management',
    'advance-payment',
    'recognition',
    'smart-hospital',
    'registration',
    'hospital-map',
    'medicine',
    'release',
    'visiting-person',
    'outpatient-pay',
    'department',
    'disease-bank',
    'first-aid',
    'waiting-call',
    'expense-details',
    'health-card',
    'settlement',
    'report-query'
  ],
  filled: [
    // has corresponding outline icon
    'user',
    'music',
    'voice',
    'delete2',
    'info',
    'star',
    'warning',
    'volume',
    'volume2',
    'wap-home',
    'video',
    'vedio2',
    'off-phone',
    'phone',
    'completed',
    'up',
    'down',
    'right',
    'clear',
    'clock',
    'checked',
    // 'multiple-checked',
    'photograph',
    'browsing-history',
    'photo',
    'more',
    // 'chinese-medicine',
    // 'eye-plastic-surgery',
    // 'oph-special',
    // 'team-clinic',
    // 'diabetic-fundus',
    // 'diabetic-uveitis',
    // 'glaucoma',
    // 'myopia',
    // 'dry-eye',
    // 'cataract',
    // 'intensive-care',
    // 'surgical',
    // 'oncology',
    // 'traditional-chinese',
    // 'chinese-western',
    // 'poison-follow-up',
    // 'treatment-center',
    // 'plastic-surgery',
    // 'acupuncture',
    // 'sports-injury',
    // 'gene',
    // 'ophthalmology',
    // 'dialysis',
    // 'blood-rheumatoid',
    // 'blood',
    // 'vascular-surgery',
    // 'cardiology',
    // 'cardiology-center',
    // 'cardiothoracic',
    // 'child-massage',
    // 'child',
    // 'child-orthopedics',
    // 'digestive-endoscopy',
    // 'gastroent',
    // 'microbone',
    // 'thyroid',
    // 'mini-orthopedics',
    // 'massage',
    // 'pain',
    // 'diabetic-foot',
    // 'hand',
    // 'reproductive',
    // 'nephrology',
    // 'neurosurgery',
    // 'neurology',
    // 'neurology2',
    // 'psychiatric',
    // 'burn',
    // 'wound-stoma',
    // 'hernia',
    // 'breast-surgery',
    // 'general',
    // 'general-surgery',
    // 'punek',
    // 'skin',
    // 'endocrine',
    // 'andrology',
    // 'maternal-child',
    // 'urology',
    // 'anesthesia',
    // 'tumor-radiation',
    // 'clinical-nutrition',
    // 'geriatrics',
    // 'oral-cavity',
    // 'rehabilitation',
    // 'mental-health',
    // 'psychiatry',
    // 'tuberculosis',
    // 'health-management',
    // 'family-plan',
    // 'firstaid-car',
    // 'spine',
    // 'respiratory',
    // 'nuclear',
    // 'arthrosis',
    // 'orthopedics',
    // 'orth',
    // 'high-pressure',
    // 'anorectal-surgery',
    // 'hepa',
    // 'hepa-radiation',
    // 'hepa-surgery',
    // 'liver',
    // 'gynecology',
    // 'maternity',
    // 'rheumatic',
    // 'heat',
    // 'otolaryngology',
    // 'moxibustion',
    // 'metabolism',
    // 'trauma',
    // 'infection',
    // 'pathology',
    // 'health-care'
  ]
};
